import type { TrendTemplate } from '@/types';

export const trendTemplates: TrendTemplate[] = [
  {
    id: 'i-close-my-eyes',
    name: 'I close my eyes...',
    description: 'Lifestyle photos with dreamy text, ending with your app screenshot. The viral format that got 3M+ views for the "Been" app.',
    category: 'lifestyle',
    viralScore: 9,
    tags: ['travel', 'lifestyle', 'dreamy', 'emotional'],
    suggestedMusic: ['A Million Dreams', 'Close Eyes - DVRST', 'Daylight - David Kushner'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'I close my eyes',
        suggestedImagePrompt: 'aesthetic lifestyle photo in a beautiful location, museum, nature, or city, warm tones, cinematic',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 36, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 45 }, textAlign: 'center' },
      },
      {
        suggestedText: 'and I can see...',
        suggestedImagePrompt: 'stunning travel destination photo, golden hour, person looking into the distance, aspirational',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 36, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 30 }, textAlign: 'center' },
      },
      {
        suggestedText: '',
        suggestedImagePrompt: '',
        transition: 'fade',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#333333', position: { x: 50, y: 20 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'pov-you-just',
    name: 'POV: you just...',
    description: 'Point-of-view narrative that sets up a relatable scenario, then reveals your app as the natural solution.',
    category: 'pov',
    viralScore: 8,
    tags: ['relatable', 'narrative', 'solution', 'problem-solving'],
    suggestedMusic: ['Metamorphosis - Interworld', 'After Dark - Mr.Kitty'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'POV: you just bought a new product',
        suggestedImagePrompt: 'person holding a product box or shopping bag, candid moment, natural lighting',
        transition: 'slide-left',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 32, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 35 }, textAlign: 'center' },
      },
      {
        suggestedText: "but you can't understand the ingredients",
        suggestedImagePrompt: 'close-up of someone reading a product label with confused expression, slightly blurred background',
        transition: 'slide-left',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 32, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 35 }, textAlign: 'center' },
      },
      {
        suggestedText: 'so you scan it',
        suggestedImagePrompt: '',
        transition: 'slide-left',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#333333', position: { x: 50, y: 15 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'things-that-make-sense',
    name: 'Things that make sense in 2026',
    description: 'A list-style slideshow of smart life choices, with your app as one of them on the final slide.',
    category: 'list',
    viralScore: 8,
    tags: ['list', 'smart', 'modern', 'life-hack'],
    suggestedMusic: ['Aesthetic - Tollan Kim', 'Money Trees - Kendrick Lamar'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'Things that just make sense in 2026',
        suggestedImagePrompt: 'clean minimalist flat lay of modern essentials, top view, soft lighting',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 34, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: 'Checking what you put on your skin',
        suggestedImagePrompt: 'skincare products arranged neatly on marble surface, clean aesthetic',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 30, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: 'Having an app that does it for you',
        suggestedImagePrompt: 'person using smartphone, close-up of screen, modern lifestyle',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 30, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: '',
        suggestedImagePrompt: '',
        transition: 'fade',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#333333', position: { x: 50, y: 20 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'nobody-asked',
    name: 'Nobody asked but...',
    description: 'Casual, humble-brag style that feels authentic. Share something cool, then casually show your app.',
    category: 'lifestyle',
    viralScore: 7,
    tags: ['casual', 'authentic', 'humble', 'discovery'],
    suggestedMusic: ['Chill Guy - anonymous', 'Lofi beats'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: "Nobody asked but here's my favorite app lately",
        suggestedImagePrompt: 'cozy desk setup or lifestyle scene, phone visible, warm ambient lighting',
        transition: 'fade',
        duration: 4,
        isAppPromo: false,
        textStyle: { fontSize: 30, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: '',
        suggestedImagePrompt: '',
        transition: 'fade',
        duration: 5,
        isAppPromo: true,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#333333', position: { x: 50, y: 15 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'this-changed-my-life',
    name: 'This changed my life',
    description: 'Before/after transformation story. Show the pain, then the solution (your app).',
    category: 'reaction',
    viralScore: 9,
    tags: ['transformation', 'before-after', 'emotional', 'impact'],
    suggestedMusic: ['Runaway - Aurora', 'Ceilings - Lizzy McAlpine'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'Me before vs after finding this app',
        suggestedImagePrompt: 'split image or before/after concept, dramatic mood difference',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 32, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 35 }, textAlign: 'center' },
      },
      {
        suggestedText: 'Before: chaos',
        suggestedImagePrompt: 'messy, overwhelming scene related to the product niche, cluttered, stressful vibe',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 30, fontWeight: 700, color: '#ff6b6b', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: 'After: clarity',
        suggestedImagePrompt: '',
        transition: 'fade',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 30, fontWeight: 700, color: '#51cf66', position: { x: 50, y: 15 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'rate-my-routine',
    name: 'Rate my routine / setup',
    description: 'Gallery-style showcase asking for engagement. Gallery of your process, ending with app reveal.',
    category: 'lifestyle',
    viralScore: 7,
    tags: ['engagement', 'gallery', 'routine', 'setup'],
    suggestedMusic: ['Taste - Sabrina Carpenter', 'Espresso - Sabrina Carpenter'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'Rate my skincare routine',
        suggestedImagePrompt: 'aesthetic bathroom shelfie with skincare products, soft warm lighting',
        transition: 'slide-left',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 34, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 30 }, textAlign: 'center' },
      },
      {
        suggestedText: 'Step 1: research every ingredient',
        suggestedImagePrompt: 'hand holding a product, reading the back label, clean bright photo',
        transition: 'slide-left',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: 'The app that makes it easy',
        suggestedImagePrompt: '',
        transition: 'slide-left',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#333333', position: { x: 50, y: 15 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'tell-me-without-telling-me',
    name: 'Tell me without telling me',
    description: 'Metaphorical reveal. Show the vibe, the feeling, the aesthetic — then reveal the app that makes it possible.',
    category: 'reaction',
    viralScore: 7,
    tags: ['metaphor', 'aesthetic', 'reveal', 'mysterious'],
    suggestedMusic: ['Sweater Weather - The Neighbourhood', 'Heather - Conan Gray'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: "Tell me you care about your skin without telling me",
        suggestedImagePrompt: 'glass skin close-up, dewy, glowing, natural beauty, soft focus',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 35 }, textAlign: 'center' },
      },
      {
        suggestedText: '',
        suggestedImagePrompt: '',
        transition: 'fade',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#333333', position: { x: 50, y: 15 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'difference-between',
    name: 'The difference between X and Y',
    description: 'Comparison format that positions your app as the smarter choice. Educational and engaging.',
    category: 'comparison',
    viralScore: 8,
    tags: ['comparison', 'educational', 'smart-choice', 'informative'],
    suggestedMusic: ['Cradles - Sub Urban', 'Industry Baby - Lil Nas X'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'Guessing if a product is safe vs actually knowing',
        suggestedImagePrompt: 'person looking confused at store shelf full of products, overwhelmed',
        transition: 'slide-left',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 28, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 35 }, textAlign: 'center' },
      },
      {
        suggestedText: 'The difference is one scan',
        suggestedImagePrompt: '',
        transition: 'slide-left',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 30, fontWeight: 700, color: '#333333', position: { x: 50, y: 15 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'what-x-gets-you',
    name: 'What $X gets you',
    description: 'Value proposition format. Show what a small price gets you — ending with your app as the best deal.',
    category: 'comparison',
    viralScore: 8,
    tags: ['value', 'price', 'deal', 'comparison'],
    suggestedMusic: ['Rich Flex - Drake', 'Money - Lisa'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'What $5/month gets you',
        suggestedImagePrompt: 'luxury lifestyle collage, coffee, skincare, phone, modern aesthetic',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 34, fontWeight: 700, color: '#ffffff', position: { x: 50, y: 35 }, textAlign: 'center' },
      },
      {
        suggestedText: 'Know every ingredient in your products',
        suggestedImagePrompt: 'person confidently reading product, informed consumer, bright confident mood',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: '',
        suggestedImagePrompt: '',
        transition: 'fade',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#333333', position: { x: 50, y: 20 }, textAlign: 'center' },
      },
    ],
  },
  {
    id: 'day-in-my-life',
    name: 'Day in my life as a...',
    description: 'Story-driven format showing daily life, naturally integrating your app as part of the routine.',
    category: 'story',
    viralScore: 8,
    tags: ['story', 'daily-life', 'routine', 'authentic'],
    suggestedMusic: ['Good Days - SZA', 'Golden Hour - JVKE'],
    suggestedPlatforms: ['9:16'],
    slides: [
      {
        suggestedText: 'Day in my life as someone who actually reads labels',
        suggestedImagePrompt: 'morning routine scene, sunlit bathroom or kitchen, fresh and clean aesthetic',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 28, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 35 }, textAlign: 'center' },
      },
      {
        suggestedText: 'Step 1: scan everything',
        suggestedImagePrompt: 'hand holding phone scanning a product, lifestyle photography, bright',
        transition: 'fade',
        duration: 3,
        isAppPromo: false,
        textStyle: { fontSize: 30, fontWeight: 600, color: '#ffffff', position: { x: 50, y: 40 }, textAlign: 'center' },
      },
      {
        suggestedText: 'My secret weapon',
        suggestedImagePrompt: '',
        transition: 'fade',
        duration: 4,
        isAppPromo: true,
        textStyle: { fontSize: 30, fontWeight: 700, color: '#333333', position: { x: 50, y: 15 }, textAlign: 'center' },
      },
    ],
  },
];
